# Generated by Django 5.0.6 on 2024-06-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("description", models.TextField()),
                ("transcript", models.TextField()),
                ("audio", models.BinaryField()),
            ],
        ),
    ]
